// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Server Streaming/greetpbServerStreaming/greet.proto

package greetpbServerStream

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_c3e06b84b59f7fba, []int{0}
}
func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (dst *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(dst, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_c3e06b84b59f7fba, []int{1}
}
func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (dst *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(dst, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_c3e06b84b59f7fba, []int{2}
}
func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (dst *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(dst, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greetServerStream.Greeting")
	proto.RegisterType((*GreetRequest)(nil), "greetServerStream.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "greetServerStream.GreetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetServiceClient interface {
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (GreetService_GreetClient, error)
}

type greetServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetServiceClient(cc *grpc.ClientConn) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (GreetService_GreetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[0], "/greetServerStream.GreetService/Greet", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_GreetClient interface {
	Recv() (*GreetResponse, error)
	grpc.ClientStream
}

type greetServiceGreetClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetClient) Recv() (*GreetResponse, error) {
	m := new(GreetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServiceServer is the server API for GreetService service.
type GreetServiceServer interface {
	Greet(*GreetRequest, GreetService_GreetServer) error
}

func RegisterGreetServiceServer(s *grpc.Server, srv GreetServiceServer) {
	s.RegisterService(&_GreetService_serviceDesc, srv)
}

func _GreetService_Greet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).Greet(m, &greetServiceGreetServer{stream})
}

type GreetService_GreetServer interface {
	Send(*GreetResponse) error
	grpc.ServerStream
}

type greetServiceGreetServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetServer) Send(m *GreetResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _GreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greetServerStream.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Greet",
			Handler:       _GreetService_Greet_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Server Streaming/greetpbServerStreaming/greet.proto",
}

func init() {
	proto.RegisterFile("Server Streaming/greetpbServerStreaming/greet.proto", fileDescriptor_greet_c3e06b84b59f7fba)
}

var fileDescriptor_greet_c3e06b84b59f7fba = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbf, 0x4f, 0x84, 0x30,
	0x14, 0xc7, 0xc5, 0x44, 0x02, 0x4f, 0x1d, 0xac, 0xd1, 0x18, 0x89, 0x91, 0x74, 0xd1, 0x09, 0x0d,
	0x0c, 0xee, 0x0e, 0xb2, 0x31, 0xc0, 0xe6, 0xa0, 0x29, 0xe6, 0xd9, 0x34, 0x81, 0x82, 0x6d, 0xf1,
	0xef, 0xbf, 0xb4, 0x94, 0xcb, 0xe5, 0xee, 0x18, 0xbf, 0x3f, 0xf2, 0xfd, 0xbc, 0x3c, 0x28, 0x1a,
	0x54, 0xff, 0xa8, 0xd2, 0xc6, 0x28, 0x64, 0xbd, 0x90, 0xfc, 0x85, 0x2b, 0x44, 0x33, 0xb6, 0xb3,
	0xbf, 0x67, 0x67, 0xa3, 0x1a, 0xcc, 0x40, 0xae, 0x9c, 0xd8, 0x6d, 0xd0, 0x0f, 0x88, 0x4a, 0x6b,
	0x0a, 0xc9, 0xc9, 0x03, 0xc0, 0xaf, 0x50, 0xda, 0x7c, 0x4b, 0xd6, 0xe3, 0x5d, 0x90, 0x06, 0xcf,
	0x71, 0x1d, 0x3b, 0xa7, 0x62, 0x3d, 0x92, 0x04, 0xe2, 0x8e, 0x2d, 0xe9, 0xa9, 0x4b, 0x23, 0x6b,
	0xd8, 0x90, 0x96, 0x70, 0xe1, 0x76, 0x6a, 0xfc, 0x9b, 0x50, 0x1b, 0xf2, 0x06, 0x11, 0xf7, 0xbb,
	0x6e, 0xe9, 0x3c, 0x4f, 0xb2, 0x03, 0x7a, 0xb6, 0xa0, 0xeb, 0x6d, 0x99, 0x3e, 0xc1, 0xa5, 0x1f,
	0xd2, 0xe3, 0x20, 0x35, 0x92, 0x5b, 0x08, 0x15, 0xea, 0xa9, 0x33, 0xfe, 0x22, 0xaf, 0xf2, 0x2f,
	0x4f, 0xb4, 0x83, 0xe2, 0x07, 0x49, 0x05, 0x67, 0x4e, 0x93, 0xc7, 0x35, 0x90, 0xbf, 0xed, 0x3e,
	0x5d, 0x2f, 0xcc, 0x4c, 0x7a, 0xf2, 0x1a, 0xbc, 0xdf, 0x7c, 0x5e, 0x1f, 0x79, 0x69, 0x1b, 0xba,
	0x57, 0x16, 0x9b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xb8, 0xeb, 0xec, 0x81, 0x01, 0x00, 0x00,
}
