// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Calculator/calculatorpb/calculator.proto

package calculatorpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CalculationRequest struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculationRequest) Reset()         { *m = CalculationRequest{} }
func (m *CalculationRequest) String() string { return proto.CompactTextString(m) }
func (*CalculationRequest) ProtoMessage()    {}
func (*CalculationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_calculator_25609691b8721e75, []int{0}
}
func (m *CalculationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculationRequest.Unmarshal(m, b)
}
func (m *CalculationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculationRequest.Marshal(b, m, deterministic)
}
func (dst *CalculationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculationRequest.Merge(dst, src)
}
func (m *CalculationRequest) XXX_Size() int {
	return xxx_messageInfo_CalculationRequest.Size(m)
}
func (m *CalculationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculationRequest proto.InternalMessageInfo

func (m *CalculationRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *CalculationRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type CalculationResponse struct {
	AddResult            int32    `protobuf:"varint,1,opt,name=add_result,json=addResult,proto3" json:"add_result,omitempty"`
	SubtractResult       int32    `protobuf:"varint,2,opt,name=subtract_result,json=subtractResult,proto3" json:"subtract_result,omitempty"`
	MultiplyResult       int32    `protobuf:"varint,3,opt,name=multiply_result,json=multiplyResult,proto3" json:"multiply_result,omitempty"`
	DivideResult         int32    `protobuf:"varint,4,opt,name=divide_result,json=divideResult,proto3" json:"divide_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculationResponse) Reset()         { *m = CalculationResponse{} }
func (m *CalculationResponse) String() string { return proto.CompactTextString(m) }
func (*CalculationResponse) ProtoMessage()    {}
func (*CalculationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_calculator_25609691b8721e75, []int{1}
}
func (m *CalculationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculationResponse.Unmarshal(m, b)
}
func (m *CalculationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculationResponse.Marshal(b, m, deterministic)
}
func (dst *CalculationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculationResponse.Merge(dst, src)
}
func (m *CalculationResponse) XXX_Size() int {
	return xxx_messageInfo_CalculationResponse.Size(m)
}
func (m *CalculationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculationResponse proto.InternalMessageInfo

func (m *CalculationResponse) GetAddResult() int32 {
	if m != nil {
		return m.AddResult
	}
	return 0
}

func (m *CalculationResponse) GetSubtractResult() int32 {
	if m != nil {
		return m.SubtractResult
	}
	return 0
}

func (m *CalculationResponse) GetMultiplyResult() int32 {
	if m != nil {
		return m.MultiplyResult
	}
	return 0
}

func (m *CalculationResponse) GetDivideResult() int32 {
	if m != nil {
		return m.DivideResult
	}
	return 0
}

func init() {
	proto.RegisterType((*CalculationRequest)(nil), "calculator.CalculationRequest")
	proto.RegisterType((*CalculationResponse)(nil), "calculator.CalculationResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Ops(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*CalculationResponse, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Ops(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*CalculationResponse, error) {
	out := new(CalculationResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Ops", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	Ops(context.Context, *CalculationRequest) (*CalculationResponse, error)
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Ops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Ops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Ops",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Ops(ctx, req.(*CalculationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ops",
			Handler:    _CalculatorService_Ops_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Calculator/calculatorpb/calculator.proto",
}

func init() {
	proto.RegisterFile("Calculator/calculatorpb/calculator.proto", fileDescriptor_calculator_25609691b8721e75)
}

var fileDescriptor_calculator_25609691b8721e75 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcb, 0x4a, 0x03, 0x31,
	0x14, 0x86, 0x1d, 0xab, 0x82, 0xc7, 0x69, 0xc5, 0xb8, 0x11, 0xc1, 0xdb, 0x74, 0x61, 0x57, 0x15,
	0xf4, 0x0d, 0x74, 0xe3, 0x4a, 0x61, 0xdc, 0x89, 0x52, 0x32, 0xc9, 0x11, 0x02, 0x69, 0x12, 0x73,
	0x29, 0xf8, 0x4c, 0xbe, 0xa4, 0x90, 0xd3, 0x38, 0x23, 0xd2, 0x5d, 0xf2, 0xe5, 0xcb, 0x4f, 0xf2,
	0x1f, 0x98, 0x3d, 0x70, 0x2d, 0x92, 0xe6, 0xd1, 0xfa, 0x1b, 0xf1, 0xbb, 0x74, 0xdd, 0x60, 0x33,
	0x77, 0xde, 0x46, 0xcb, 0xa0, 0x27, 0xcd, 0x1b, 0xb0, 0x72, 0x4f, 0x59, 0xd3, 0xe2, 0x67, 0xc2,
	0x10, 0xd9, 0x15, 0xd4, 0x1f, 0xca, 0x87, 0xb8, 0x30, 0x69, 0xd9, 0xa1, 0x3f, 0xa9, 0x2e, 0xab,
	0xd9, 0x6e, 0x7b, 0x90, 0xd9, 0x53, 0x46, 0x6c, 0x0a, 0xe3, 0x80, 0xc2, 0x1a, 0x59, 0x9c, 0xed,
	0xec, 0xd4, 0x04, 0x49, 0x6a, 0xbe, 0x2b, 0x38, 0xfe, 0x13, 0x1f, 0x9c, 0x35, 0x01, 0xd9, 0x19,
	0x00, 0x97, 0x72, 0xe1, 0x31, 0x24, 0x1d, 0xd7, 0xe9, 0xfb, 0x5c, 0xca, 0x36, 0x03, 0x76, 0x0d,
	0x87, 0x21, 0x75, 0xd1, 0x73, 0x11, 0x8b, 0x43, 0xe9, 0x93, 0x82, 0x7b, 0x71, 0x99, 0x74, 0x54,
	0x4e, 0x7f, 0x15, 0x71, 0x44, 0x62, 0xc1, 0x6b, 0x71, 0x0a, 0x63, 0xa9, 0x56, 0x4a, 0x62, 0xd1,
	0x76, 0xe8, 0xb5, 0x04, 0x49, 0xba, 0x7d, 0x87, 0xa3, 0xbe, 0xc3, 0x17, 0xf4, 0x2b, 0x25, 0x90,
	0x3d, 0xc2, 0xe8, 0xd9, 0x05, 0x76, 0x3e, 0x1f, 0xd4, 0xf8, 0xbf, 0xb1, 0xd3, 0x8b, 0x8d, 0xe7,
	0xf4, 0xe5, 0x66, 0xeb, 0x7e, 0xf2, 0x5a, 0x0f, 0xe7, 0xd2, 0xed, 0xe5, 0x69, 0xdc, 0xfd, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xb3, 0x6d, 0xf5, 0xa6, 0xb9, 0x01, 0x00, 0x00,
}
